fix: ext-12-fix-testnet-smart-contracts
Insrt-Finance/insrt-v2-contracts pull request #233
Opened 2024-07-15 10:11 UTC by giovannifranchi

Changes implemented:

- The main root of error lies in the fact that the gnosis multisig in not registered as a client in the Supra Deposit contract. This process can only be done by the client trough the following [form](https://supra.com/docs/vrf/vrf-subscription-model/)

- The other problem related to the after deployment scripts for Blast and Base was the fact that the script was using safeBatch package which does not support the target chains. 

![batch-script](https://github.com/threesigmaxyz/insrt-v2-contracts/assets/116166763/a0e9a88e-3455-42c2-b418-3fb3732ebb16)

- The script is now creating a pending transaction in the gnosis multisig wallet that needs to be then confirmed individually by the other signers.

- Additionally a code snippet for executing the whole transactions has been added. Note this code can only work if all signers PKs are provided in the .env file

2024-07-17 11:36 UTC, 0xinsi requested changes
Generally looks good.

Please ensure `make prettier` is run - it seems that the formatting is different between two almost identical files.

Has this been run on a testnet and verified?

Additionally, could another script be added which just sets values on testnets (ie tenderly testnets) rather than submitting txs?

2024-07-17 11:36 UTC, 0xinsi commented on script/Base/post-deployment/01_configureVRFSubscription.s.sol
> +        // This version is makes possible to directly make the gnosis safe execute the transactions required by broadcasting the transactions for each signer.
There will never be an instance where a single `.env` file holds multiple multisig signer PKs - it seems this is in stark contrast to general security practices.

Please remove the commented code.

2024-07-17 11:36 UTC, 0xinsi commented on script/Blast/post-deployment/02_configureVRFSubscription.s.sol
> +        // This version is makes possible to directly make the gnosis safe execute the transactions required by broadcasting the transactions for each signer.
Similar as above.

2024-07-18 11:19 UTC, giovannifranchi commented
They cannot be tested because as stated in the previous comment, Supra client whitelisting is centralised and needs to pass trough a form that gets sent to the Supra team. This needs to be done by the protocol owner. Furthermore developing that kind of script would not provide in my opinion any type of insight on the side of contract testing. Doing such a thing would just take a snapshot of the blockchain at that moment but will not be able to perform scenarios related to the Supra service since most of that part happens off-chain

2024-07-18 11:26 UTC, closed without merging